name: Create Production Deployment
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  create_deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: amondnet/vercel-action@v25.2.0
        id: vercel-deploy
        with:
          vercel-token: ${{secrets.VERCEL_TOKEN}}
          github-token: ${{secrets.GITHUB_TOKEN}}
          vercel-org-id: ${{secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{secrets.VERCEL_PROJECT_ID}}
          vercel-args: --prod --confirm
